name: 'elinter CI'
on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - '**.org'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: cachix/install-nix-action@v10
      - uses: actions/checkout@v2
      - uses: akirak/elinter@v4
      - run: elinter -t ert -e latest -- reformatter-tests.el
